// The deployed protocol indexer, defined once.
//
// Imported by BOTH the runtime transport (src/api/indexerHttpClient.ts) and
// orval.config.ts, so the client is always generated from the same deployment
// it will call. Kept free of `import.meta.env` so the Node-side config can
// import it.
//
// This is Railway's autogenerated hostname; replace it with the custom domain
// once the indexer's CNAME is cut over. Overridable per environment via
// VITE_PROTOCOL_INDEXER_API at runtime and PROTOCOL_INDEXER_API_URL at codegen.
export const DEFAULT_INDEXER_API = "https://api-production-ca6c.up.railway.app";
